#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  # mac
  chromedriver "$@"
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
  # linux
  ./chromedriver.gnu "$@"
elif [[ "$OSTYPE" == "msys" ]]; then
  # MinGW
  chromedriver.exe "$@"
else
  # Unknown OS
  echo "UNKNOWN OS"
fi
