export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const CHANGE_SEARCH_ZIPCODE = 'CHANGE_SEARCH_ZIPCODE';

export const FETCH_JOBS_PENDING = 'FETCH_JOBS_PENDING';
export const FETCHED_JOBS_SUCCESS = "FETCHED_JOBS_SUCCESS";
export const FETCHED_JOBS_FAILED = "FETCHED_JOBS_FAILED";

export const FETCH_ORGANIZATIONS_PENDING = 'FETCH_ORGANIZATIONS_PENDING';
export const FETCHED_ORGANIZATIONS_SUCCESS = "FETCHED_ORGANIZATIONS_SUCCESS";
export const FETCHED_ORGANIZATIONS_FAILED = "FETCHED_ORGANIZATIONS_FAILED";

export const CHANGE_EMPLOYMENT_TYPE_FT = 'CHANGE_EMPLOYMENT_TYPE_FT';
export const CHANGE_EMPLOYMENT_TYPE_PT = 'CHANGE_EMPLOYMENT_TYPE_PT';

export const CHANGE_DISTANCE = 'CHANGE_DISTANCE';
// export const CHANGE_DISTANCE_25 = 'CHANGE_DISTANCE_25';
// export const CHANGE_DISTANCE_OVER50 = 'CHANGE_DISTANCE_OVER50';
