export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const FETCH_JOBS_PENDING = 'FETCH_JOBS_PENDING';
export const FETCHED_JOBS_SUCCESS = "FETCHED_JOBS_SUCCESS";
export const FETCHED_JOBS_FAILED = "FETCHED_JOBS_FAILED";